# $FreeBSD$

.PATH: ${.CURDIR}/../../dev/broadcom/chipcommon

KMOD=	bcm_chipcommon
SRCS=	bcm_chipcommon.c bcm_chipcommon_reg.h bcm_chipcommon_var.h
SRCS+=	device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
